name: horstl_wrapper
description: Wrapper for the online student organization system (horstl.hs-fulda.de) of the University Fulda.
# version: 0.0.1
# homepage: https://elcapitan.io
# author: Yannic Wehner<yannic.wehner@pm.me>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  html: ^0.14.0+3
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
